### ISSUE TITLE
`bootcluster` parameter

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#15]
This code here uses a `bootcluster` variable that is from the original R code coming from a pre-processed object. 

According to the software website it is:

> allows the user to specify subclusters via the bootcluster argument.

Can you explain that?

https://github.com/s3alfisc/wildboottest/blob/b33df5fca1ea72986b47d33ebc575bc4068b4d81/src/boot_algo3.py#L33

**Comment by amichuda** [comment]
NVM I assume this is all in the Mackinnon, Nielsen and Webb (2022) paper?

**Comment by s3alfisc** [comment]
The bootcluster variable is only relevant for multiway clustering - i.e when clustering in more than one dimension, it is not clear if the bootstrap weights should be drawn based based on the first clustering variable, the second clustering variable, or the intersection of both. For now, we can always set it to `bootcluster = cluster`. There is more info on this in the "fast and wild" paper, or in [MacKinnon & Webb's](https://academic.oup.com/ectj/article-abstract/21/2/114/5078969?login=false) paper on the subcluster bootstrap, which makes the case that if there are only very few clusters, one might consider to use a “subcluster” as the level from which the bootstrap weights are drawn, where a subcluster is a partition of a cluster, i.e. cities in a given state.

**Comment by s3alfisc** [comment]
Where did you see NVM? Quite likely that I meant MNW instead 😄

**Comment by s3alfisc** [comment]
Close for now - we'll have to get back to this once we allow multiway clustering.
