### ISSUE TITLE
Implement Unit Tests

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/wildboottest#21]
For features in version 0.1: 

Test the bootstrap algos against R & Julia. strategy: create data + run algo in R, Julia, Python + save all scrips + hard-code test values (or safe in file) for actual tests. 

- [ ] Potentially set up CI via github actions (?)
- [ ] Potentially set up codecov (?)

Implement the following tests - each for different weights, bootstrap types, null on dgp, etc...

External Tests: 
- [x] Using full enumeration, are bootstrapped t-statistics exactly identical between R, Julia, Python when using the same small sample corrections? 
- [x] When `full_enumeration  = False`, are bootstrapped p-values almost identical? Are non-bootstrapped t-stats exactly identical?  

Internal Tests: 
- [x] #49
- [x] #48

**Comment by amichuda** [comment]
How do `test_r_vs_py_deterministic` and  `test_r_vs_py_stochastic` differ? It seems like `test_r_vs_py_stochastic` includes the deterministic part, or no?

**Comment by s3alfisc** [comment]
Hi, in the 'deterministic' test, we have 'full enumeration', i.e. with 5 clusters and rademacher weights, we always run the bootstrap with the exact same weights matrix. In consequence, the bootstrapped test statistics should be *exactly identical*, which I approximate with a MSE of less than e^-15. For the stochastic test with G = 25, all bootstrap weights matrices v will be different, so we basically test for convergence in probability. These tests will not pass a MSE < e^-15 tests but rather a e^-2 test.

**Comment by amichuda** [comment]
So can I put those two functions together and have different thresholds depending on `full_enumeration == True` or not? We should probably also have an error if you use `full_enumeration` with anything other `rademacher`. Correct me if I'm wrong?

**Comment by s3alfisc** [comment]
Hi, yes, in principle this could be combined, but note that full enumeration is not an argument that the user chooses but automatically turned on when 2^G < # boot iter & rademacher weights are used. We should probably send a message to the user in case this happens (which is what fwildclusterboot & boottest do).

**Comment by s3alfisc** [comment]
Also, there are probably much  better ways to test for exact equality than through mse < e-15, I was just in "get-a-lot-done-quickly" mode back when I implemented this and did not spend much time into getting to know Python functionality for making comparisons.

**Comment by amichuda** [comment]
Yeah that's all right, `mse` is fine. I think for next time, there `np.isclose` https://numpy.org/doc/stable/reference/generated/numpy.isclose.html

**Comment by amichuda** [comment]
So are the "external tests" supposed to be captured by those two functions?

**Comment by s3alfisc** [comment]
Yes! External is now well covered.

**Comment by s3alfisc** [comment]
Close for now, as I think the package is sufficiently tested for a v0.1 release.
