### ISSUE TITLE
Publish `wildboottest` on pypi

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#28]
What do you think about publishing  so that `statsmodels` can add it to dependencies?

**Comment by s3alfisc** [comment]
In general, yes, let's do it!

Not sure about the pypy standards - is it ok to publish somewhat immature packages? 

There are a few things that I would like us to check / add beforehand: 

- [ ] implement proper tests against one other implementation
- [ ] Check that using incorrect arguments to 'wildboottest()' return appropriate error messages, i.e. bootstrap types x3 are not yet supported 
- [ ] Maybe format the output of the function in a nicer way, ie return a dictionary or DataFrame? 
- [ ] Take another look at the documentation and see if it is clear and correct 

This all should not take a lot of time (probably 2-3 hours?).

**Comment by amichuda** [comment]
I like these action items and agree completely. Let's do these items, publish to PyPi, and do the PR. 

PyPi doesn't really have standards like that. You can publish packages in any form. But it's up to you whether you think people should use it!

**Comment by amichuda** [comment]
added issues for each action item

**Comment by s3alfisc** [comment]
Hi @amichuda - I have now uploaded `wildboottest` to [testpypi](https://test.pypi.org/project/wildboottest/0.1.0/). Please take a look at it, then we can properly upload to pypi. :)

**Comment by s3alfisc** [comment]
One issue definitely is that you do not seem to be mentioned as a developer - we really need to change that!

**Comment by s3alfisc** [comment]
I took another look at the docstrings at some point, and they looked 'good enough' for a version 0.1 to me.
