### ISSUE TITLE
wildboottest without clusters

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#44]
Should we allow for no cluster input, and in which case, does it just turn into a regular wild bootstrap? Or should there be an error?

**Comment by s3alfisc** [comment]
Yes, that would be the idea - if no cluster is provided, run a heteroskedastic bootstrap. In principle, all algorithms as implemtend right now will work - we just would have to create a variable `clustid = bootclustid = list(range(0, N))`. But this will be very slow, so I thought I'd simply implement what I have in [fwildclusterboot ](https://github.com/s3alfisc/fwildclusterboot/blob/176a4e9348fce72ac03e84477d7f221ff3602cdb/src/wildboottest.cpp#L84).
