### ISSUE TITLE
`self.k` should be defined by `X` not `R`

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#45]
@s3alfisc 

Since `self.k` is used for creating matrices and such for `X`, should we redefine `self.k = self.X.shape[1]`, not `self.k = self.R.shape[0]`, and then make an error if `self.k != self.R.shape[0]`. 

I think this makes more sense, since the user can make a mistake in defining R which might propagate through the code and show up in place not related to conducting the statistical test.

Do you concur?

**Comment by s3alfisc** [comment]
Yes, makes perfect sense!
