### ISSUE TITLE
does seeding work? E.g. same seeds -> same results, different seeds -> different results?

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#48]

**Comment by s3alfisc** [comment]
Also one thing to check: seeding and function scope, e.g. does setting the seed outside and within the function lead to similar results? In code, does running 

```
import numpy as np
np.random.seed(42) 
wildboottest(...)
```
lead to the same results as 

```
wildboottest(..., seed = 42)
``` 
Not an important test, but part of due dilligence.
