### ISSUE TITLE
Possible type in `boot_algo3`

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#6]
@s3alfisc 

The arguments in the function reference, `N_G_bootcluster`, but the function uses two arguments, `bootcluster` and `N_G`. Was the underscore a typo?

https://github.com/s3alfisc/wildboottest/blob/b33df5fca1ea72986b47d33ebc575bc4068b4d81/src/boot_algo3.py#L3

**Comment by s3alfisc** [comment]
`N_G` is not equal to `N_G_bootcluster`: `N_G` is the number of unique values in a cluster. If e.g. there we are clustering in two dimensions, the covariance matrix is 

$$
\Sigma = \Sigma_{1} + \Sigma_{2} - \Sigma_{1,2}
$$

with $N_{G1}$, $N_{G2}$ or $N_{G12}$ clusters. The clustering variable(s) is/are usually called `clustid` in the R code (which is a bad name, it should be called cluster, as you do in your code). For oneway clustering, clustid is a dataframe with three columns, and `N_G` is of length 3. `N_G_bootcluster` instead denotes the number of unique *bootstrap clusters*, which is identical to one of the cluster variables. For oneway clustering, `N_G = N_G_bootcluster` always holds.
