### ISSUE TITLE
`fe` in `bootalgo3`

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#8]
@s3alfisc 

Is `fe` supposed to be a long variable of being in a particular entity/group (like hhids) or are they already supposed to be dummy variables?

https://github.com/s3alfisc/fwildclusterboot/blob/99f5ec51392ea70a61d0e54dc53b739de057b3b5/R/boot_algo3.R#L71

**Comment by s3alfisc** [comment]
The `fe` variable is currently not used in `boot_algo3()` - it's just a placeholer in my R code. For the future and in `wildboottest()`, I think it should be a categorical series.
