### ISSUE TITLE
Should we just assume pandas dataframes as input?

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#9]
A lot of the data inputs you have in the `boot_algo3` function in R assumes a dataframe. Should we just do the same and assume pandas dataframes in the python version? We can then turn them into numpy arrays in the function for performance.

**Comment by s3alfisc** [comment]
Yes, this sounds like a good idea to me =) Though I do think that in most cases, there is no good reason to assume a `DataFrame`, so we could also be lenient and accept both.
