### ISSUE TITLE
Update `pandas` dependency

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/wildboottest#97]
Is there anything breaking with `pandas` right now? I believe we can update it to allow `pandas == 2.1.1`

**Comment by s3alfisc** [comment]
I would also think that we can update without breaking anything. The current pandas specification is definitely too restrictive. Do you want to open a PR? Else I can do it this weekend.

**Comment by s3alfisc** [comment]
... and it's on PyPi: [link](https://pypi.org/project/wildboottest/0.3.0/) =)
